1.
INSERT INTO EMPLOYEES VALUES (
    300,
    'Snow',
    'Jack',
    'PROFESSOR',
    100,
    TO_DATE('01 05 2013', 'DD MM YYYY'),
    4750, DEFAULT,
    30
);

INSERT INTO EMPLOYEES VALUES (
    310,
    'Cook',
    'Robin',
    'PROFESSOR',
    100,
    TO_DATE('16 09 2016', 'DD MM YYYY'),
    3500,
    1250,
    40
);

INSERT INTO EMPLOYEES VALUES (
    320,
    'Dormand',
    'Francis',
    'ASSISTANT',
    110,
    TO_DATE('01 01 2018', 'DD MM YYYY'),
    3900, DEFAULT,
    40
);

SELECT
    *
FROM
    EMPLOYEES
WHERE
    EMP_ID IN ( 300, 310, 320 )

2.
    INSERT INTO DEPARTMENTS VALUES (
        70,
        'DATABASE SYSTEMS', DEFAULT
    )
3.
UPDATE EMPLOYEES
SET DEPT_ID = (SELECT DEPT_ID FROM DEPARTMENTS WHERE DEPT_NAME = 'DATABASE SYSTEMS')
WHERE EMP_ID IN (300,310,320)

4.
UPDATE EMPLOYEES
SET
    SALARY = SALARY * 1.1,
    ADD_SALARY = (
        CASE
        WHEN ADD_SALARY IS NULL THEN
        100
        ELSE
        ADD_SALARY * 1.2
        END
    )
WHERE
    EMP_ID IN ( 300, 310, 320 )

5.

DELETE FROM DEPARTMENTS
WHERE
    DEPT_NAME = 'DATABASE SYSTEMS'

MESSAGE: 
ORA-02292: naruszono więzy spójności (AI145453.FK_DEPARTMENT) - znaleziono rekord podrzędny

6.
DELETE FROM EMPLOYEES
WHERE
    DEPT_NAME = 'DATABASE SYSTEMS'

UPDATE EMPLOYEES
SET
    DEPT_ID = NULL
WHERE
    DEPT_ID = 70
7.
DELETE FROM DEPARTMENTS
WHERE
    DEPT_NAME = 'DATABASE SYSTEMS'
8&9 PASS INSTEAD DO EXERCISE FROM CHAT

UPDATE EMPLOYEES
SET
    EMPLOYEES.SALARY = EMPLOYEES.SALARY + 0.0 * (
        SELECT
            AVG(E.SALARY)
        FROM
            EMPLOYEES E
            INNER JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
        WHERE
            D.DEPT_NAME = 'ADMINISTRATION'
    )
WHERE
    DEPT_ID IN (
        SELECT
            DEPT_ID
        FROM
            DEPARTMENTS
        WHERE
            DEPT_NAME IN ( 'EXPERT SYSTEMS', 'ALGORITHMS' )
    )

10.
DELETE FROM EMPLOYEES
WHERE
    EMP_ID = 300
