(define (problem p1)
    (:domain world-of-blocks)
    (:objects a b c d e f g h)
    (:init
        (on-floor a)
        (on-floor b)
        (on-floor c)
        (on-floor d)
        (on-floor e)
        (on-floor f)
        (on-floor g)
        (on-floor h)
        (clear a)
        (clear b)
        (clear c)
        (clear d)
        (clear e)
        (clear f)
        (clear g)
        (clear h)
    )
    (:goal
        (and
            (not (on-floor a))
            (not (on-floor b))
            (not (on-floor c))
            (not (on-floor d))
            (not (on-floor e))
            (not (on-floor f))
            (not (on-floor g))
            (not (in-air))
        )
    )
)