---
title: "R Notebook"
output: html_notebook
---

## Exercise 1

```{r}
one_hot <- function(t){
  k<-max(t)
  mx = sapply(t, function(x){
    vec = rep(0,k)
    vec[x] = 1
    vec
  })
  t(mx)
}

one_hot_2 <- function(t){
  k<-max(t)
  n <-length(t)
  R<- rep(0,k*n)
  dim(R) <-c(n,k)
  R[cbind(1:n, t)] <- 1
  R
}


one_hot(c(1,2,3,4,1,1,1,1))
one_hot_2(c(1,2,3,4,1,1,1,1))
```

## Exercise 2
```{r}
my_softmax <-function(X){
  mx <- apply(exp(X), 1, function(x){
    x/sum(x)
  })
  t(mx)
}

my_softmax_2 <-function(X){
  Y <- exp(X)
  Y/rowSums()
}

one_hot_smax <-function(X){
   apply(X, 1, function(x){
     which.min(abs(x-1))# or which.max()
  })
}

X <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)
X
#my_softmax(X)
one_hot_smax(my_softmax(X))

X <- matrix(c(7,5,6,1,2,5,1,1, 3), nrow = 3, ncol = 3, byrow = TRUE)
X
#my_softmax(X)
one_hot_smax(my_softmax(X))
```

## Exercise 3
```{r}
b_min_max <- function(X){
  apply(X,2,function(x){
    c(min(x),max(x))
  })
}

X <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)
X
b_min_max(X)
```

## Exercise 4
```{r}
distance <- function(X,y){
  apply(X, 1, function(x){
    sqrt(sum((x-y)^2))
  })
}

distance2 <- function(X,y){
  sqrt(rowSums(t(t(X) - y)^2))
}

X <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)
X
distance(X,c(1,2,3))
distance2(X,c(1,2,3))
```

## Exercise 5
```{r}
#a)
niezaleznosc <- function(P){
  x <- rowSums(P)
  y <- colSums(P)
  X = matrix(x, ncol = 1)
  Y = matrix(y, nrow = 1)
  all((A - X%*%Y) < 1e-12)
}

A = matrix(c(1/2,0,1/4,1/4), nrow =2, ncol =2)
niezaleznosc(A)
A = matrix(c(1/4,1/4,1/4,1/4), nrow =2, ncol =2)
niezaleznosc(A)

#b
stats <- function(P, x, y){
  Xp = rowSums(P)
  Yp = colSums(P)
  ex = sum(x*Xp)
  ey = sum(y*Yp)
  print(paste("EX: ", ex))
  print(paste("EY: ", ey))
  ex2 = sum(x*x*Xp)
  ey2 = sum(y*y*Yp)
  varx = ex2 - ex^2
  vary = ey2 - ey^2
  print(paste("Var X: ", varx))
  print(paste("Var Y: ", vary))
  cov = t(t(A*x)*y)
  print(paste("COV: ",cov))
  print(paste("COR: ", cov/sqrt(varx*vary)))
}

stats(A, c(1,3), c(5,7))
```

## Exercise 6
```{r}
movingavg <- function(x, k){
  n = length(x)
  print(n)
  rowSums(sapply(1:k, function(i){
    x[i:(n-k+i)]
  }))
}
plot(movingavg(UKgas, 20))
```

## Exercise 7
```{r}
airports = read.csv('../data/nycflights13_airports.csv.gz', comment.char="#")
#a
airports[sample(1:nrow(airports),100),]
#b
airports[sample(1:nrow(airports),floor(nrow(airports)*0.05)),]
#c
head(airports,100)
#d
tail(airports,100)
```

## Exercise 8
```{r}
winequality = read.csv('../data/winequality-all.csv', comment.char="#")
test_ids = sample(1:nrow(winequality),floor(nrow(winequality)*0.2))
test_set = winequality[test_ids,]
train_set = winequality[-test_ids,]
nrow(test_set)
nrow(train_set)
```

## Exercise 9
```{r}
library(fueleconomy)
vehicles = fueleconomy::vehicles
z_cty = (vehicles$cty- mean(vehicles$cty))/sd(vehicles$cty)
z_hwy = (vehicles$hwy- mean(vehicles$hwy))/sd(vehicles$hwy)
cbind(vehicles,z_cty,z_hwy)

#or

vehicles$z_cty = z_cty
vehicles$z_hwy = z_hwy
vehicles
```

## Exercise 10
```{r}
rozwin <- function(M, names){
  a1 = stack(data.frame(M))
  a2 = stack(data.frame(t(M)))
  res = merge(a1,a2, by = "values")
  names = c("how many", "where", "when")
  colnames(res) <- names
  res
}
rozwin(WorldPhones)
```

## Exercise 11
```{r}
zwin <- function(inputData){
  names = colnames(inputData)
  
}
rozwin(WorldPhones)
```
